### PR TITLE
[NO-TASK] Refactor PoolsManager traits

### PR DESCRIPTION
**Pull request by kurotych**
**Description:**
- Make LiquiditiPoolsManager trait inherited from PoolsManager 
- Improve calculate_exchange_rate doc

**Changes in storage or API:**

Describe storage structure changes or API changes. Make sure to update the [API docs](https://minterestfinance.atlassian.net/wiki/spaces/MINTEREST/pages/134807557/Minterest+API).

**Checklist**

- [ ] Code is covered with tests
- [ ] Code is covered with benchmarks
- [ ] Fresh benchmark results included

### CODE REVIEW

**Review by lut1k — DISMISSED** [review]

**Review by dev-vadim — COMMENTED** [review]
Consider the next changes:
- move pool_exists() to LiquidityPoolsManager
- remove pools_account_id() and get_pool_available_liquidity() from LiquidationPoolsManager
- make LiquidationPoolsManager inherit PoolsManager

**Comment by kurotych** [comment]
> Consider the next changes:
> 
>     * move pool_exists() to LiquidityPoolsManager
> 
>     * remove pools_account_id() and get_pool_available_liquidity() from LiquidationPoolsManager
> 
>     * make LiquidationPoolsManager inherit PoolsManager

Done

**Review by Apollo50 — COMMENTED** [review]
Maybe add fn create_pool() which is implemented in Liquidity_pool to LiquidityPoolsManager trait?

**Review by lut1k — DISMISSED** [review]

**Comment by kurotych** [comment]
> Maybe add fn create_pool() which is implemented in Liquidity_pool to LiquidityPoolsManager trait?

Done

**Review by lut1k — APPROVED** [review]

**Pull request merged**
